-- drop table messages if exists ;
CREATE TABLE IF NOT EXISTS messages (id bigint generated by default as identity (start with 1), message VARCHAR(100));
-- INSERT INTO messages(message) VALUES ('Message')